name: trigger_action
description: A sample Polymer application
dependencies:
  core_elements: '>=0.4.0+6 <0.5.0'
  paper_elements: '>=0.5.0 <0.6.0'
  polymer: '>=0.15.1+5 <0.16.0'
transformers:
- polymer:
    entry_points: [web/index.html, web/local_index.html]
